# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couch_docs}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Strom"]
  s.date = %q{2010-08-03}
  s.default_executable = %q{couch-docs}
  s.description = %q{Provides a simple means for working with CouchDB documents on the filesystem.  It can dump CouchDB documents and design documents in discrete chunks.  Conversely it can read JSON and .js files from the filesystem to be pushed to a CouchDB database.}
  s.email = %q{eee.c@eeecooks.com}
  s.executables = ["couch-docs"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".bnsignore",
     ".gitignore",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/couch-docs",
     "couch_docs.gemspec",
     "fixtures/_design/__lib/foo.js",
     "fixtures/_design/a/b/c.js",
     "fixtures/_design/a/b/d.js",
     "fixtures/_design/a/e.json",
     "fixtures/_design/j/q.json",
     "fixtures/_design/x/z.js",
     "fixtures/bar.json",
     "fixtures/baz_with_attachments.json",
     "fixtures/baz_with_attachments/spacer.gif",
     "fixtures/foo.json",
     "lib/couch_docs.rb",
     "lib/couch_docs/command_line.rb",
     "lib/couch_docs/design_directory.rb",
     "lib/couch_docs/document_directory.rb",
     "lib/couch_docs/store.rb",
     "spec/couch_docs/command_line_spec.rb",
     "spec/couch_docs/design_directory_spec.rb",
     "spec/couch_docs/document_directory_spec.rb",
     "spec/couch_docs/store_spec.rb",
     "spec/couch_docs_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "test/test_couch_docs.rb"
  ]
  s.homepage = %q{http://github.com/eee-c/couch_docs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Manage CouchDB views and documents.}
  s.test_files = [
    "spec/couch_docs/command_line_spec.rb",
     "spec/couch_docs/design_directory_spec.rb",
     "spec/couch_docs/document_directory_spec.rb",
     "spec/couch_docs/store_spec.rb",
     "spec/couch_docs_spec.rb",
     "spec/spec_helper.rb",
     "test/test_couch_docs.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.5.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<directory_watcher>, ["= 1.3.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rest-client>, [">= 1.5.1"])
      s.add_dependency(%q<json>, [">= 1.2.0"])
      s.add_dependency(%q<directory_watcher>, ["= 1.3.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rest-client>, [">= 1.5.1"])
    s.add_dependency(%q<json>, [">= 1.2.0"])
    s.add_dependency(%q<directory_watcher>, ["= 1.3.1"])
  end
end

